# Generated by Django 2.0.1 on 2019-04-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20190426_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintracker',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.assistant'),
        ),
    ]
