# Generated by Django 2.0.1 on 2019-05-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20190508_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintracker',
            name='log_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='logintracker',
            name='log_out',
            field=models.DateTimeField(null=True),
        ),
    ]
