# Generated by Django 2.0.1 on 2019-05-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20190427_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintracker',
            name='log_out',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
