# Generated by Django 2.0.1 on 2019-05-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20190501_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintracker',
            name='log_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
